version: '2'
services:
  chat:
    image: ruby:latest
    command: bin/server -b 0.0.0.0 -p 8080
    working_dir: /usr/src/app
    volumes:
      - "$PWD:/usr/src/app"
    ports:
      - "8080:8080"
    environment:
      - RAILS_ENV=development
      - RAILS_DATABASE_HOST=database
    depends_on:
      - database
    restart: always
  database:
    image: mysql:5.6
    volumes:
      - '/var/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
