default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: <%= ENV['RAILS_DATABASE_HOST'] %>

development:
  <<: *default
  database: rails-chat_development

test:
  <<: *default
  database: rails-chat_test

production:
  <<: *default
  database: rails-chat_production
  username: rails-chat
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
